### ISSUE TITLE
Tweetable highlight is misbehaving

### ISSUE THREAD

**Issue by patygomes** [edsurge/adaptive_learning#8]
1. It's covering everything that comes on the right (we may have it the same way we had in our design mock up or we may put it on the right and increase the left margin of the quotes);
2. It's not respecting proportions when we change the resolution of the pages.

![screen shot 2016-01-05 at 14 35 55](https://cloud.githubusercontent.com/assets/10470191/12129868/47640bca-b3bb-11e5-8a00-f614a0d23948.png)

**Comment by br80** [comment]
Resolved
